# alias swagger="docker run --rm -it -e GOPATH=$HOME/eanson/go:/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
swagger:
# 需要先安装docker swagger  [href](https://goswagger.io/install.html)
	swagger generate spec -o ./swagger.yaml --scan-models